function showhidegtnv(){
		var dm = document.frmUpdate;
		dm.gtnv.style.display = "block";
		dm.tthn.style.display = "none"
		dm.cnnv.style.display = "none";
		dm.ccnv.style.display = "none";
		dm.dvdbnv.style.display = "none";
		document.getElementById("cmndnv").style.display = "none";
		dm.nccmndnv.style.display = "none";
		dm.shcnv.style.display = "none";
		dm.nchcnv.style.display = "none";
		dm.mtgnv.style.display = "none";
		dm.dtllnv.style.display = "none";
		dm.dcthtnv.style.display = "none";
		dm.dtddnv.style.display = "none";
		dm.dcttnv.style.display = "none";
		dm.emailnv.style.display = "none";
		dm.dcllnv.style.display = "none";
		dm.websitenv.style.display = "none";
		document.getElementById("nvd").style.display = "none";
		document.getElementById("nvdo").style.display = "none";
		document.getElementById("nvcd").style.display = "none";
		dm.mcvdnv.style.display = "none";
		dm.mcvdonv.style.display = "none";
		dm.mcvcdnv.style.display = "none";
		dm.mttnv.style.display = "none";
		dm.stknv.style.display = "none";
		dm.nhnv.style.display = "none";
		dm.update.style.display = "block";
	}
	function showhidetthn(){
		var dm = document.frmUpdate;
		dm.tthn.style.display = "block"
		dm.ccnv.style.display = "none";
		dm.cnnv.style.display = "none";
		dm.gtnv.style.display = "none";
		dm.dvdbnv.style.display = "none";
		document.getElementById("cmndnv").style.display = "none";
		dm.nccmndnv.style.display = "none";
		dm.shcnv.style.display = "none";
		dm.nchcnv.style.display = "none";
		dm.mtgnv.style.display = "none";
		dm.dtllnv.style.display = "none";
		dm.dcthtnv.style.display = "none";
		dm.dtddnv.style.display = "none";
		dm.dcttnv.style.display = "none";
		dm.emailnv.style.display = "none";
		dm.dcllnv.style.display = "none";
		dm.websitenv.style.display = "none";
		document.getElementById("nvd").style.display = "none";
		document.getElementById("nvdo").style.display = "none";
		document.getElementById("nvcd").style.display = "none";
		dm.mcvdnv.style.display = "none";
		dm.mcvdonv.style.display = "none";
		dm.mcvcdnv.style.display = "none";
		dm.mttnv.style.display = "none";
		dm.stknv.style.display = "none";
		dm.nhnv.style.display = "none";
		dm.update.style.display = "block";
	}
	function showhidecnnv(){
		var dm = document.frmUpdate;
		dm.cnnv.style.display = "block";
		dm.tthn.style.display = "none"
		dm.ccnv.style.display = "none";
		dm.dvdbnv.style.display = "none";
		dm.gtnv.style.display = "none";
		document.getElementById("cmndnv").style.display = "none";
		dm.nccmndnv.style.display = "none";
		dm.shcnv.style.display = "none";
		dm.nchcnv.style.display = "none";
		dm.mtgnv.style.display = "none";
		dm.dtllnv.style.display = "none";
		dm.dcthtnv.style.display = "none";
		dm.dtddnv.style.display = "none";
		dm.dcttnv.style.display = "none";
		dm.emailnv.style.display = "none";
		dm.dcllnv.style.display = "none";
		dm.websitenv.style.display = "none";
		document.getElementById("nvd").style.display = "none";
		document.getElementById("nvdo").style.display = "none";
		document.getElementById("nvcd").style.display = "none";
		dm.mcvdnv.style.display = "none";
		dm.mcvdonv.style.display = "none";
		dm.mcvcdnv.style.display = "none";
		dm.mttnv.style.display = "none";
		dm.stknv.style.display = "none";
		dm.nhnv.style.display = "none";
		dm.update.style.display = "block";
	}
	function showhidedvdb(){
		var dm = document.frmUpdate;
		dm.dvdbnv.style.display = "block";
		dm.cnnv.style.display = "none";
		dm.tthn.style.display = "none"
		dm.ccnv.style.display = "none";
		dm.gtnv.style.display = "none";
		document.getElementById("cmndnv").style.display = "none";
		dm.nccmndnv.style.display = "none";
		dm.shcnv.style.display = "none";
		dm.nchcnv.style.display = "none";
		dm.mtgnv.style.display = "none";
		dm.dtllnv.style.display = "none";
		dm.dcthtnv.style.display = "none";
		dm.dtddnv.style.display = "none";
		dm.dcttnv.style.display = "none";
		dm.emailnv.style.display = "none";
		dm.dcllnv.style.display = "none";
		dm.websitenv.style.display = "none";
		document.getElementById("nvd").style.display = "none";
		document.getElementById("nvdo").style.display = "none";
		document.getElementById("nvcd").style.display = "none";
		dm.mcvdnv.style.display = "none";
		dm.mcvdonv.style.display = "none";
		dm.mcvcdnv.style.display = "none";
		dm.mttnv.style.display = "none";
		dm.stknv.style.display = "none";
		dm.nhnv.style.display = "none";
		dm.update.style.display = "block";
	}
	function showhideccnv(){
		var dm = document.frmUpdate;
		dm.ccnv.style.display = "block";
		dm.tthn.style.display = "none"
		dm.cnnv.style.display = "none";
		dm.gtnv.style.display = "none";
		dm.dvdbnv.style.display = "none";
		document.getElementById("cmndnv").style.display = "none";
		dm.nccmndnv.style.display = "none";
		dm.shcnv.style.display = "none";
		dm.nchcnv.style.display = "none";
		dm.mtgnv.style.display = "none";
		dm.dtllnv.style.display = "none";
		dm.dcthtnv.style.display = "none";
		dm.dtddnv.style.display = "none";
		dm.dcttnv.style.display = "none";
		dm.emailnv.style.display = "none";
		dm.dcllnv.style.display = "none";
		dm.websitenv.style.display = "none";
		document.getElementById("nvd").style.display = "none";
		document.getElementById("nvdo").style.display = "none";
		document.getElementById("nvcd").style.display = "none";
		dm.mcvdnv.style.display = "none";
		dm.mcvdonv.style.display = "none";
		dm.mcvcdnv.style.display = "none";
		dm.mttnv.style.display = "none";
		dm.stknv.style.display = "none";
		dm.nhnv.style.display = "none";
		dm.update.style.display = "block";
	}
	function showhidecmnd(){
		var dm = document.frmUpdate;
		document.getElementById("cmndnv").style.display = "block";
		dm.ccnv.style.display = "none";
		dm.tthn.style.display = "none"
		dm.cnnv.style.display = "none";
		dm.gtnv.style.display = "none";
		dm.dvdbnv.style.display = "none";
		dm.nccmndnv.style.display = "none";
		dm.shcnv.style.display = "none";
		dm.nchcnv.style.display = "none";
		dm.mtgnv.style.display = "none";
		dm.dtllnv.style.display = "none";
		dm.dcthtnv.style.display = "none";
		dm.dtddnv.style.display = "none";
		dm.dcttnv.style.display = "none";
		dm.emailnv.style.display = "none";
		dm.dcllnv.style.display = "none";
		dm.websitenv.style.display = "none";
		document.getElementById("nvd").style.display = "none";
		document.getElementById("nvdo").style.display = "none";
		document.getElementById("nvcd").style.display = "none";
		dm.mcvdnv.style.display = "none";
		dm.mcvdonv.style.display = "none";
		dm.mcvcdnv.style.display = "none";
		dm.mttnv.style.display = "none";
		dm.stknv.style.display = "none";
		dm.nhnv.style.display = "none";
		dm.update.style.display = "block";
	}
	function showhidenccmnd(){
		var dm = document.frmUpdate;
		dm.nccmndnv.style.display = "block";
		document.getElementById("cmndnv").style.display = "none";
		dm.ccnv.style.display = "none";
		dm.tthn.style.display = "none"
		dm.cnnv.style.display = "none";
		dm.gtnv.style.display = "none";
		dm.dvdbnv.style.display = "none";
		dm.shcnv.style.display = "none";
		dm.nchcnv.style.display = "none";
		dm.mtgnv.style.display = "none";
		dm.dtllnv.style.display = "none";
		dm.dcthtnv.style.display = "none";
		dm.dtddnv.style.display = "none";
		dm.dcttnv.style.display = "none";
		dm.emailnv.style.display = "none";
		dm.dcllnv.style.display = "none";
		dm.websitenv.style.display = "none";
		document.getElementById("nvd").style.display = "none";
		document.getElementById("nvdo").style.display = "none";
		document.getElementById("nvcd").style.display = "none";
		dm.mcvdnv.style.display = "none";
		dm.mcvdonv.style.display = "none";
		dm.mcvcdnv.style.display = "none";
		dm.mttnv.style.display = "none";
		dm.stknv.style.display = "none";
		dm.nhnv.style.display = "none";
		dm.update.style.display = "block";
	}
	function showhidepassport(){
		var dm = document.frmUpdate;
		dm.shcnv.style.display = "block";
		dm.nccmndnv.style.display = "none";
		document.getElementById("cmndnv").style.display = "none";
		dm.ccnv.style.display = "none";
		dm.tthn.style.display = "none"
		dm.cnnv.style.display = "none";
		dm.gtnv.style.display = "none";
		dm.dvdbnv.style.display = "none";
		dm.nchcnv.style.display = "none";
		dm.mtgnv.style.display = "none";
		dm.dtllnv.style.display = "none";
		dm.dcthtnv.style.display = "none";
		dm.dtddnv.style.display = "none";
		dm.dcttnv.style.display = "none";
		dm.emailnv.style.display = "none";
		dm.dcllnv.style.display = "none";
		dm.websitenv.style.display = "none";
		document.getElementById("nvd").style.display = "none";
		document.getElementById("nvdo").style.display = "none";
		document.getElementById("nvcd").style.display = "none";
		dm.mcvdnv.style.display = "none";
		dm.mcvdonv.style.display = "none";
		dm.mcvcdnv.style.display = "none";
		dm.mttnv.style.display = "none";
		dm.stknv.style.display = "none";
		dm.nhnv.style.display = "none";
		dm.update.style.display = "block";
	}
	function showhidencpassport(){
		var dm = document.frmUpdate;
		dm.nchcnv.style.display = "block";
		dm.shcnv.style.display = "none";
		dm.nccmndnv.style.display = "none";
		document.getElementById("cmndnv").style.display = "none";
		dm.ccnv.style.display = "none";
		dm.tthn.style.display = "none"
		dm.cnnv.style.display = "none";
		dm.gtnv.style.display = "none";
		dm.dvdbnv.style.display = "none";
		dm.mtgnv.style.display = "none";
		dm.dtllnv.style.display = "none";
		dm.dcthtnv.style.display = "none";
		dm.dtddnv.style.display = "none";
		dm.dcttnv.style.display = "none";
		dm.emailnv.style.display = "none";
		dm.dcllnv.style.display = "none";
		dm.websitenv.style.display = "none";
		document.getElementById("nvd").style.display = "none";
		document.getElementById("nvdo").style.display = "none";
		document.getElementById("nvcd").style.display = "none";
		dm.mcvdnv.style.display = "none";
		dm.mcvdonv.style.display = "none";
		dm.mcvcdnv.style.display = "none";
		dm.mttnv.style.display = "none";
		dm.stknv.style.display = "none";
		dm.nhnv.style.display = "none";
		dm.update.style.display = "block";
	}
	function showhidemtg(){
		var dm = document.frmUpdate;
		dm.mtgnv.style.display = "block";
		dm.nchcnv.style.display = "none";
		dm.shcnv.style.display = "none";
		dm.nccmndnv.style.display = "none";
		document.getElementById("cmndnv").style.display = "none";
		dm.ccnv.style.display = "none";
		dm.tthn.style.display = "none"
		dm.cnnv.style.display = "none";
		dm.gtnv.style.display = "none";
		dm.dvdbnv.style.display = "none";
		dm.dtllnv.style.display = "none";
		dm.dcthtnv.style.display = "none";
		dm.dtddnv.style.display = "none";
		dm.dcttnv.style.display = "none";
		dm.emailnv.style.display = "none";
		dm.dcllnv.style.display = "none";
		dm.websitenv.style.display = "none";
		document.getElementById("nvd").style.display = "none";
		document.getElementById("nvdo").style.display = "none";
		document.getElementById("nvcd").style.display = "none";
		dm.mcvdnv.style.display = "none";
		dm.mcvdonv.style.display = "none";
		dm.mcvcdnv.style.display = "none";
		dm.mttnv.style.display = "none";
		dm.stknv.style.display = "none";
		dm.nhnv.style.display = "none";
		dm.update.style.display = "block";
	}
	function showhidedtll(){
		var dm = document.frmUpdate;
		dm.dtllnv.style.display = "block";
		dm.mtgnv.style.display = "none";
		dm.nchcnv.style.display = "none";
		dm.shcnv.style.display = "none";
		dm.nccmndnv.style.display = "none";
		document.getElementById("cmndnv").style.display = "none";
		dm.ccnv.style.display = "none";
		dm.tthn.style.display = "none"
		dm.cnnv.style.display = "none";
		dm.gtnv.style.display = "none";
		dm.dvdbnv.style.display = "none";
		dm.dcthtnv.style.display = "none";
		dm.dtddnv.style.display = "none";
		dm.dcttnv.style.display = "none";
		dm.emailnv.style.display = "none";
		dm.dcllnv.style.display = "none";
		dm.websitenv.style.display = "none";
		document.getElementById("nvd").style.display = "none";
		document.getElementById("nvdo").style.display = "none";
		document.getElementById("nvcd").style.display = "none";
		dm.mcvdnv.style.display = "none";
		dm.mcvdonv.style.display = "none";
		dm.mcvcdnv.style.display = "none";
		dm.mttnv.style.display = "none";
		dm.stknv.style.display = "none";
		dm.nhnv.style.display = "none";
		dm.update.style.display = "block";
	}
	function showhidedctht(){
		var dm = document.frmUpdate;
		dm.dcthtnv.style.display = "block";
		dm.dtllnv.style.display = "none";
		dm.mtgnv.style.display = "none";
		dm.nchcnv.style.display = "none";
		dm.shcnv.style.display = "none";
		dm.nccmndnv.style.display = "none";
		document.getElementById("cmndnv").style.display = "none";
		dm.ccnv.style.display = "none";
		dm.tthn.style.display = "none"
		dm.cnnv.style.display = "none";
		dm.gtnv.style.display = "none";
		dm.dvdbnv.style.display = "none";
		dm.dtddnv.style.display = "none";
		dm.dcttnv.style.display = "none";
		dm.emailnv.style.display = "none";
		dm.dcllnv.style.display = "none";
		dm.websitenv.style.display = "none";
		document.getElementById("nvd").style.display = "none";
		document.getElementById("nvdo").style.display = "none";
		document.getElementById("nvcd").style.display = "none";
		dm.mcvdnv.style.display = "none";
		dm.mcvdonv.style.display = "none";
		dm.mcvcdnv.style.display = "none";
		dm.mttnv.style.display = "none";
		dm.stknv.style.display = "none";
		dm.nhnv.style.display = "none";
		dm.update.style.display = "block";
	}
	function showhidemobile(){
		var dm = document.frmUpdate;
		dm.dtddnv.style.display = "block";
		dm.dcthtnv.style.display = "none";
		dm.dtllnv.style.display = "none";
		dm.mtgnv.style.display = "none";
		dm.nchcnv.style.display = "none";
		dm.shcnv.style.display = "none";
		dm.nccmndnv.style.display = "none";
		document.getElementById("cmndnv").style.display = "none";
		dm.ccnv.style.display = "none";
		dm.tthn.style.display = "none"
		dm.cnnv.style.display = "none";
		dm.gtnv.style.display = "none";
		dm.dvdbnv.style.display = "none";
		dm.dcttnv.style.display = "none";
		dm.emailnv.style.display = "none";
		dm.dcllnv.style.display = "none";
		dm.websitenv.style.display = "none";
		document.getElementById("nvd").style.display = "none";
		document.getElementById("nvdo").style.display = "none";
		document.getElementById("nvcd").style.display = "none";
		dm.mcvdnv.style.display = "none";
		dm.mcvdonv.style.display = "none";
		dm.mcvcdnv.style.display = "none";
		dm.mttnv.style.display = "none";
		dm.stknv.style.display = "none";
		dm.nhnv.style.display = "none";
		dm.update.style.display = "block";
	}
	function showhidedctt(){
		var dm = document.frmUpdate;
		dm.dcttnv.style.display = "block";
		dm.dtddnv.style.display = "none";
		dm.dcthtnv.style.display = "none";
		dm.dtllnv.style.display = "none";
		dm.mtgnv.style.display = "none";
		dm.nchcnv.style.display = "none";
		dm.shcnv.style.display = "none";
		dm.nccmndnv.style.display = "none";
		document.getElementById("cmndnv").style.display = "none";
		dm.ccnv.style.display = "none";
		dm.tthn.style.display = "none"
		dm.cnnv.style.display = "none";
		dm.gtnv.style.display = "none";
		dm.dvdbnv.style.display = "none";
		dm.emailnv.style.display = "none";
		dm.dcllnv.style.display = "none";
		dm.websitenv.style.display = "none";
		document.getElementById("nvd").style.display = "none";
		document.getElementById("nvdo").style.display = "none";
		document.getElementById("nvcd").style.display = "none";
		dm.mcvdnv.style.display = "none";
		dm.mcvdonv.style.display = "none";
		dm.mcvcdnv.style.display = "none";
		dm.mttnv.style.display = "none";
		dm.stknv.style.display = "none";
		dm.nhnv.style.display = "none";
		dm.update.style.display = "block";
	}
	function showhideemail(){
		var dm = document.frmUpdate;
		dm.emailnv.style.display = "block";
		dm.dcttnv.style.display = "none";
		dm.dtddnv.style.display = "none";
		dm.dcthtnv.style.display = "none";
		dm.dtllnv.style.display = "none";
		dm.mtgnv.style.display = "none";
		dm.nchcnv.style.display = "none";
		dm.shcnv.style.display = "none";
		dm.nccmndnv.style.display = "none";
		document.getElementById("cmndnv").style.display = "none";
		dm.ccnv.style.display = "none";
		dm.tthn.style.display = "none"
		dm.cnnv.style.display = "none";
		dm.gtnv.style.display = "none";
		dm.dvdbnv.style.display = "none";
		dm.dcllnv.style.display = "none";
		dm.websitenv.style.display = "none";
		document.getElementById("nvd").style.display = "none";
		document.getElementById("nvdo").style.display = "none";
		document.getElementById("nvcd").style.display = "none";
		dm.mcvdnv.style.display = "none";
		dm.mcvdonv.style.display = "none";
		dm.mcvcdnv.style.display = "none";
		dm.mttnv.style.display = "none";
		dm.stknv.style.display = "none";
		dm.nhnv.style.display = "none";
		dm.update.style.display = "block";
	}
	function showhidedcll(){
		var dm = document.frmUpdate;
		dm.dcllnv.style.display = "block";
		dm.emailnv.style.display = "none";
		dm.dcttnv.style.display = "none";
		dm.dtddnv.style.display = "none";
		dm.dcthtnv.style.display = "none";
		dm.dtllnv.style.display = "none";
		dm.mtgnv.style.display = "none";
		dm.nchcnv.style.display = "none";
		dm.shcnv.style.display = "none";
		dm.nccmndnv.style.display = "none";
		document.getElementById("cmndnv").style.display = "none";
		dm.ccnv.style.display = "none";
		dm.tthn.style.display = "none"
		dm.cnnv.style.display = "none";
		dm.gtnv.style.display = "none";
		dm.dvdbnv.style.display = "none";
		dm.websitenv.style.display = "none";
		document.getElementById("nvd").style.display = "none";
		document.getElementById("nvdo").style.display = "none";
		document.getElementById("nvcd").style.display = "none";
		dm.mcvdnv.style.display = "none";
		dm.mcvdonv.style.display = "none";
		dm.mcvcdnv.style.display = "none";
		dm.mttnv.style.display = "none";
		dm.stknv.style.display = "none";
		dm.nhnv.style.display = "none";
		dm.update.style.display = "block";
	}
	function showhidewebsite(){
		var dm = document.frmUpdate;
		dm.websitenv.style.display = "block";
		dm.dcllnv.style.display = "none";
		dm.emailnv.style.display = "none";
		dm.dcttnv.style.display = "none";
		dm.dtddnv.style.display = "none";
		dm.dcthtnv.style.display = "none";
		dm.dtllnv.style.display = "none";
		dm.mtgnv.style.display = "none";
		dm.nchcnv.style.display = "none";
		dm.shcnv.style.display = "none";
		dm.nccmndnv.style.display = "none";
		document.getElementById("cmndnv").style.display = "none";
		dm.ccnv.style.display = "none";
		dm.tthn.style.display = "none"
		dm.cnnv.style.display = "none";
		dm.gtnv.style.display = "none";
		dm.dvdbnv.style.display = "none";
		document.getElementById("nvd").style.display = "none";
		document.getElementById("nvdo").style.display = "none";
		document.getElementById("nvcd").style.display = "none";
		dm.mcvdnv.style.display = "none";
		dm.mcvdonv.style.display = "none";
		dm.mcvcdnv.style.display = "none";
		dm.mttnv.style.display = "none";
		dm.stknv.style.display = "none";
		dm.nhnv.style.display = "none";
		dm.update.style.display = "block";
	}
	function showhidenvd(){
		var dm = document.frmUpdate;
		document.getElementById("nvd").style.display = "block";
		dm.websitenv.style.display = "none";
		dm.dcllnv.style.display = "none";
		dm.emailnv.style.display = "none";
		dm.dcttnv.style.display = "none";
		dm.dtddnv.style.display = "none";
		dm.dcthtnv.style.display = "none";
		dm.dtllnv.style.display = "none";
		dm.mtgnv.style.display = "none";
		dm.nchcnv.style.display = "none";
		dm.shcnv.style.display = "none";
		dm.nccmndnv.style.display = "none";
		document.getElementById("cmndnv").style.display = "none";
		dm.ccnv.style.display = "none";
		dm.tthn.style.display = "none"
		dm.cnnv.style.display = "none";
		dm.gtnv.style.display = "none";
		dm.dvdbnv.style.display = "none";
		document.getElementById("nvcd").style.display = "none";
		document.getElementById("nvdo").style.display = "none";
		dm.mcvdnv.style.display = "none";
		dm.mcvdonv.style.display = "none";
		dm.mcvcdnv.style.display = "none";
		dm.mttnv.style.display = "none";
		dm.stknv.style.display = "none";
		dm.nhnv.style.display = "none";
		dm.update.style.display = "block";
	}
	function showhidenvdo(){
		var dm = document.frmUpdate;
		document.getElementById("nvdo").style.display = "block";
		document.getElementById("nvd").style.display = "none";
		dm.websitenv.style.display = "none";
		dm.dcllnv.style.display = "none";
		dm.emailnv.style.display = "none";
		dm.dcttnv.style.display = "none";
		dm.dtddnv.style.display = "none";
		dm.dcthtnv.style.display = "none";
		dm.dtllnv.style.display = "none";
		dm.mtgnv.style.display = "none";
		dm.nchcnv.style.display = "none";
		dm.shcnv.style.display = "none";
		dm.nccmndnv.style.display = "none";
		document.getElementById("cmndnv").style.display = "none";
		dm.ccnv.style.display = "none";
		dm.tthn.style.display = "none"
		dm.cnnv.style.display = "none";
		dm.gtnv.style.display = "none";
		dm.dvdbnv.style.display = "none";
		document.getElementById("nvcd").style.display = "none";
		dm.mcvdnv.style.display = "none";
		dm.mcvdonv.style.display = "none";
		dm.mcvcdnv.style.display = "none";
		dm.mttnv.style.display = "none";
		dm.stknv.style.display = "none";
		dm.nhnv.style.display = "none";
		dm.update.style.display = "block";
	}
	function showhidenvcd(){
		var dm = document.frmUpdate;
		document.getElementById("nvcd").style.display = "block";
		document.getElementById("nvdo").style.display = "none";
		document.getElementById("nvd").style.display = "none";
		dm.websitenv.style.display = "none";
		dm.dcllnv.style.display = "none";
		dm.emailnv.style.display = "none";
		dm.dcttnv.style.display = "none";
		dm.dtddnv.style.display = "none";
		dm.dcthtnv.style.display = "none";
		dm.dtllnv.style.display = "none";
		dm.mtgnv.style.display = "none";
		dm.nchcnv.style.display = "none";
		dm.shcnv.style.display = "none";
		dm.nccmndnv.style.display = "none";
		document.getElementById("cmndnv").style.display = "none";
		dm.ccnv.style.display = "none";
		dm.tthn.style.display = "none"
		dm.cnnv.style.display = "none";
		dm.gtnv.style.display = "none";
		dm.dvdbnv.style.display = "none";
		dm.mcvdnv.style.display = "none";
		dm.mcvdonv.style.display = "none";
		dm.mcvcdnv.style.display = "none";
		dm.mttnv.style.display = "none";
		dm.stknv.style.display = "none";
		dm.nhnv.style.display = "none";
		dm.update.style.display = "block";
	}
	function showhidemcvd(){
		var dm = document.frmUpdate;
		dm.mcvdnv.style.display = "block";
		document.getElementById("nvcd").style.display = "none";
		document.getElementById("nvdo").style.display = "none";
		document.getElementById("nvd").style.display = "none";
		dm.websitenv.style.display = "none";
		dm.dcllnv.style.display = "none";
		dm.emailnv.style.display = "none";
		dm.dcttnv.style.display = "none";
		dm.dtddnv.style.display = "none";
		dm.dcthtnv.style.display = "none";
		dm.dtllnv.style.display = "none";
		dm.mtgnv.style.display = "none";
		dm.nchcnv.style.display = "none";
		dm.shcnv.style.display = "none";
		dm.nccmndnv.style.display = "none";
		document.getElementById("cmndnv").style.display = "none";
		dm.ccnv.style.display = "none";
		dm.tthn.style.display = "none"
		dm.cnnv.style.display = "none";
		dm.gtnv.style.display = "none";
		dm.dvdbnv.style.display = "none";
		dm.mcvdonv.style.display = "none";
		dm.mcvcdnv.style.display = "none";
		dm.mttnv.style.display = "none";
		dm.stknv.style.display = "none";
		dm.nhnv.style.display = "none";
		dm.update.style.display = "block";
	}
	function showhidemcvdo(){
		var dm = document.frmUpdate;
		dm.mcvdonv.style.display = "block";
		dm.mcvdnv.style.display = "none";
		document.getElementById("nvcd").style.display = "none";
		document.getElementById("nvdo").style.display = "none";
		document.getElementById("nvd").style.display = "none";
		dm.websitenv.style.display = "none";
		dm.dcllnv.style.display = "none";
		dm.emailnv.style.display = "none";
		dm.dcttnv.style.display = "none";
		dm.dtddnv.style.display = "none";
		dm.dcthtnv.style.display = "none";
		dm.dtllnv.style.display = "none";
		dm.mtgnv.style.display = "none";
		dm.nchcnv.style.display = "none";
		dm.shcnv.style.display = "none";
		dm.nccmndnv.style.display = "none";
		document.getElementById("cmndnv").style.display = "none";
		dm.ccnv.style.display = "none";
		dm.tthn.style.display = "none"
		dm.cnnv.style.display = "none";
		dm.gtnv.style.display = "none";
		dm.dvdbnv.style.display = "none";
		dm.mcvcdnv.style.display = "none";
		dm.mttnv.style.display = "none";
		dm.stknv.style.display = "none";
		dm.nhnv.style.display = "none";
		dm.update.style.display = "block";
	}
	function showhidemcvcd(){
		var dm = document.frmUpdate;
		dm.mcvcdnv.style.display = "block";
		dm.mcvdonv.style.display = "none";
		dm.mcvdnv.style.display = "none";
		document.getElementById("nvcd").style.display = "none";
		document.getElementById("nvdo").style.display = "none";
		document.getElementById("nvd").style.display = "none";
		dm.websitenv.style.display = "none";
		dm.dcllnv.style.display = "none";
		dm.emailnv.style.display = "none";
		dm.dcttnv.style.display = "none";
		dm.dtddnv.style.display = "none";
		dm.dcthtnv.style.display = "none";
		dm.dtllnv.style.display = "none";
		dm.mtgnv.style.display = "none";
		dm.nchcnv.style.display = "none";
		dm.shcnv.style.display = "none";
		dm.nccmndnv.style.display = "none";
		document.getElementById("cmndnv").style.display = "none";
		dm.ccnv.style.display = "none";
		dm.tthn.style.display = "none"
		dm.cnnv.style.display = "none";
		dm.gtnv.style.display = "none";
		dm.dvdbnv.style.display = "none";
		dm.mttnv.style.display = "none";
		dm.stknv.style.display = "none";
		dm.nhnv.style.display = "none";
		dm.update.style.display = "block";
	}
	function showhidemtt(){
		var dm = document.frmUpdate;
		dm.mttnv.style.display = "block";
		dm.mcvcdnv.style.display = "none";
		dm.mcvdonv.style.display = "none";
		dm.mcvdnv.style.display = "none";
		document.getElementById("nvcd").style.display = "none";
		document.getElementById("nvdo").style.display = "none";
		document.getElementById("nvd").style.display = "none";
		dm.websitenv.style.display = "none";
		dm.dcllnv.style.display = "none";
		dm.emailnv.style.display = "none";
		dm.dcttnv.style.display = "none";
		dm.dtddnv.style.display = "none";
		dm.dcthtnv.style.display = "none";
		dm.dtllnv.style.display = "none";
		dm.mtgnv.style.display = "none";
		dm.nchcnv.style.display = "none";
		dm.shcnv.style.display = "none";
		dm.nccmndnv.style.display = "none";
		document.getElementById("cmndnv").style.display = "none";
		dm.ccnv.style.display = "none";
		dm.tthn.style.display = "none"
		dm.cnnv.style.display = "none";
		dm.gtnv.style.display = "none";
		dm.dvdbnv.style.display = "none";
		dm.stknv.style.display = "none";
		dm.nhnv.style.display = "none";
		dm.update.style.display = "block";
	}
	function showhidetk(){
		var dm = document.frmUpdate;
		dm.stknv.style.display = "block";
		dm.mttnv.style.display = "none";
		dm.mcvcdnv.style.display = "none";
		dm.mcvdonv.style.display = "none";
		dm.mcvdnv.style.display = "none";
		document.getElementById("nvcd").style.display = "none";
		document.getElementById("nvdo").style.display = "none";
		document.getElementById("nvd").style.display = "none";
		dm.websitenv.style.display = "none";
		dm.dcllnv.style.display = "none";
		dm.emailnv.style.display = "none";
		dm.dcttnv.style.display = "none";
		dm.dtddnv.style.display = "none";
		dm.dcthtnv.style.display = "none";
		dm.dtllnv.style.display = "none";
		dm.mtgnv.style.display = "none";
		dm.nchcnv.style.display = "none";
		dm.shcnv.style.display = "none";
		dm.nccmndnv.style.display = "none";
		document.getElementById("cmndnv").style.display = "none";
		dm.ccnv.style.display = "none";
		dm.tthn.style.display = "none"
		dm.cnnv.style.display = "none";
		dm.gtnv.style.display = "none";
		dm.dvdbnv.style.display = "none";
		dm.nhnv.style.display = "none";
		dm.update.style.display = "block";
	}
	function showhidenh(){
		var dm = document.frmUpdate;
		dm.nhnv.style.display = "block";
		dm.stknv.style.display = "none";
		dm.mttnv.style.display = "none";
		dm.mcvcdnv.style.display = "none";
		dm.mcvdonv.style.display = "none";
		dm.mcvdnv.style.display = "none";
		document.getElementById("nvcd").style.display = "none";
		document.getElementById("nvdo").style.display = "none";
		document.getElementById("nvd").style.display = "none";
		dm.websitenv.style.display = "none";
		dm.dcllnv.style.display = "none";
		dm.emailnv.style.display = "none";
		dm.dcttnv.style.display = "none";
		dm.dtddnv.style.display = "none";
		dm.dcthtnv.style.display = "none";
		dm.dtllnv.style.display = "none";
		dm.mtgnv.style.display = "none";
		dm.nchcnv.style.display = "none";
		dm.shcnv.style.display = "none";
		dm.nccmndnv.style.display = "none";
		document.getElementById("cmndnv").style.display = "none";
		dm.ccnv.style.display = "none";
		dm.tthn.style.display = "none"
		dm.cnnv.style.display = "none";
		dm.gtnv.style.display = "none";
		dm.dvdbnv.style.display = "none";
		dm.update.style.display = "block";
	}