program HRM_30;

uses
  Forms,
  Controls,
  Dialogs,
  Classes,
  SysUtils,
  DateUtils,
  NavigatorFrameUnit in '..\Source\Common\FrameworkForms\ToolForms\NavigatorFrameUnit.pas' {NavigatorFrame: TFrame},
  ToolbarFrame in '..\Source\Common\FrameworkForms\ToolForms\ToolbarFrame.pas' {frameToolbar: TFrame},
  BaseFrm in '..\Source\Common\FrameworkForms\BaseForms\BaseFrm.pas' {frmBase},
  EditBaseFrm in '..\Source\Common\FrameworkForms\BaseForms\EditBaseFrm.pas' {frmEditBase},
  DocBaseFrm in '..\Source\Common\FrameworkForms\BaseForms\DocBaseFrm.pas' {frmDocBase},
  HRFlashFrom in '..\Source\Common\FrameworkForms\BaseForms\HRFlashFrom.pas' {HRSplash_Form},
  ListBaseFrm in '..\Source\Common\FrameworkForms\BaseForms\ListBaseFrm.pas' {frmListBase},
  Login in '..\Source\Common\FrameworkForms\BaseForms\Login.pas' {frmLogin},
  TreeBaseFrm in '..\Source\Common\FrameworkForms\BaseForms\TreeBaseFrm.pas' {frmTreeBase},
  BackupFrm in '..\Source\Common\FrameworkForms\ToolForms\BackupFrm.pas' {frmBackup},
  CaptionListForm in '..\Source\Common\FrameworkForms\ToolForms\CaptionListForm.pas' {CaptionListFrm},
  DataDisplayOptionForm in '..\Source\Common\FrameworkForms\ToolForms\DataDisplayOptionForm.pas' {frmDataDisplayOption},
  HintBoxDlg in '..\Source\Common\FrameworkForms\ToolForms\HintBoxDlg.pas' {frmHintBox},
  ImportForm in '..\Source\Common\FrameworkForms\ToolForms\ImportForm.pas' {ImportFrm},
  LookupFrm in '..\Source\Common\FrameworkForms\ToolForms\LookupFrm.pas' {Lookup},
  MsgDlgForm in '..\Source\Common\FrameworkForms\ToolForms\MsgDlgForm.pas' {MsgDlgFrm},
  MsgListForm in '..\Source\Common\FrameworkForms\ToolForms\MsgListForm.pas' {MsgListFrm},
  SQLParamForm in '..\Source\Common\FrameworkForms\ToolForms\SQLParamForm.pas' {frmSQLParam},
  SQLToolForm in '..\Source\Common\FrameworkForms\ToolForms\SQLToolForm.pas' {frmSQLTool},
  EditorForm in '..\Source\Common\FrameworkForms\EditorUtilityForms\EditorForm.pas' {frmEditor},
  DocumentEditorForm in '..\Source\Common\FrameworkForms\EditorUtilityForms\DocumentEditorForm.pas' {frmDocumentEditor},
  ListManageForm in '..\Source\Common\FrameworkForms\ListManagerForms\ListManageForm.pas' {frmListManager},
  StringConst in '..\Source\Common\FrameworkForms\MainForms\StringConst.pas',
  MainDM in '..\Source\Common\FrameworkForms\MainForms\MainDM.pas' {dmMain: TDataModule},
  md5 in '..\Source\Common\FrameworkForms\MainForms\md5.pas',
  SSP_Library in '..\Source\Common\FrameworkForms\MainForms\SSP_Library.pas',
  SSP_Script in '..\Source\Common\FrameworkForms\MainForms\SSP_Script.pas',
  FunctionListForm in '..\Source\Common\FrameworkForms\ReportUtilityForms\FunctionListForm.pas' {frmFunctionList},
  ListFrm in '..\Source\Common\FrameworkForms\ReportUtilityForms\ListFrm.pas' {frmList},
  ReportCaptionDefineForm in '..\Source\Common\FrameworkForms\ReportUtilityForms\ReportCaptionDefineForm.pas' {frmReportCaptionDefine},
  ReportParamsFrm in '..\Source\Common\FrameworkForms\ReportUtilityForms\ReportParamsFrm.pas' {frmReportParams},
  ReportsFrmMain in '..\Source\Common\FrameworkForms\ReportUtilityForms\ReportsFrmMain.pas' {frmReportsMain},
  SearchInfoForm in '..\Source\Common\FrameworkForms\SearchUtilityForms\SearchInfoForm.pas' {frmSearhUtils},
  SearchUnit in '..\Source\Common\FrameworkForms\SearchUtilityForms\SearchUnit.pas',
  SSP_Menus in '..\Source\Common\FrameworkForms\SSPLibrary\SSP_Menus.pas',
  ChangePass in '..\Source\Common\FrameworkForms\SystemForms\ChangePass.pas' {frmChangePass},
  ConfigFrm in '..\Source\Common\FrameworkForms\SystemForms\ConfigFrm.pas' {frmSystemConfig},
  InserUserForm in '..\Source\Common\FrameworkForms\SystemForms\InserUserForm.pas' {frmInsertUser},
  LookAndFeelDetail in '..\Source\Common\FrameworkForms\SystemForms\LookAndFeelDetail.pas' {frmLookAndFeelDetail},
  SecurityForm in '..\Source\Common\FrameworkForms\SystemForms\SecurityForm.pas' {frmSecurity},
  SysInfoForm in '..\Source\Common\FrameworkForms\SystemForms\SysInfoForm.pas' {frmSysInfo},
  TranslateCaptionForm in '..\Source\Common\FrameworkForms\SystemForms\TranslateCaptionForm.pas' {frmTranslateCaption},
  UIConfigForm in '..\Source\Common\FrameworkForms\SystemForms\UIConfigForm.pas' {frmUIConfig},
  ContractDataModule in '..\Source\Common\ContractManagerForms\ContractDataModule.pas' {ContractDM: TDataModule},
  ContractMakerForm in '..\Source\Common\ContractManagerForms\ContractMakerForm.pas' {frmContractMaker},
  ContractManageForm in '..\Source\Common\ContractManagerForms\ContractManageForm.pas' {frmContractManager},
  ContractTypeForm in '..\Source\Common\ContractManagerForms\ContractTypeForm.pas' {frmContractType},
  CanhbaoVitriCTForm in '..\Source\Common\DecisionManagerForms\CanhbaoVitriCTForm.pas' {frmCanhbaoVitriCT},
  DecisionDataModule in '..\Source\Common\DecisionManagerForms\DecisionDataModule.pas' {DecisionDM: TDataModule},
  DecisionLevelForm in '..\Source\Common\DecisionManagerForms\DecisionLevelForm.pas' {frmDecisionLevel},
  DecisionMakerForm in '..\Source\Common\DecisionManagerForms\DecisionMakerForm.pas' {frmDecisionMaker},
  DecisionManageForm in '..\Source\Common\DecisionManagerForms\DecisionManageForm.pas' {frmDecisionManager},
  DecisionTypeListForm in '..\Source\Common\DecisionManagerForms\DecisionTypeListForm.pas' {frmDecisionType},
  DisciplineForm in '..\Source\Common\DecisionManagerForms\DisciplineForm.pas' {frmDisciplineForm},
  DisciplineListForm in '..\Source\Common\DecisionManagerForms\DisciplineListForm.pas' {frmDisciplineList},
  FormalParamForm in '..\Source\Common\DecisionManagerForms\FormalParamForm.pas' {frmFormalParam},
  RewardForm in '..\Source\Common\DecisionManagerForms\RewardForm.pas' {frmRewardForm},
  RewardListForm in '..\Source\Common\DecisionManagerForms\RewardListForm.pas' {frmRewardList},
  CareerListForm in '..\Source\Common\EmployeeManagerForms\CareerListForm.pas' {frmCareerList},
  CareerTypeListForm in '..\Source\Common\EmployeeManagerForms\CareerTypeListForm.pas' {frmCareerTypeList},
  CurrencyListForm in '..\Source\Common\EmployeeManagerForms\CurrencyListForm.pas' {frmCurrencyList},
  DescentListForm in '..\Source\Common\EmployeeManagerForms\DescentListForm.pas' {frmDescentList},
  DocTemplateListForm in '..\Source\Common\EmployeeManagerForms\DocTemplateListForm.pas' {frmDocTemplateList},
  EduFieldListForm in '..\Source\Common\EmployeeManagerForms\EduFieldListForm.pas' {frmEduFieldList},
  EduLevelListForm in '..\Source\Common\EmployeeManagerForms\EduLevelListForm.pas' {frmEduLevelList},
  EmpAbility in '..\Source\Common\EmployeeManagerForms\EmpAbility.pas' {frmEmpAbility},
  EmpDocPrintForm in '..\Source\Common\EmployeeManagerForms\EmpDocPrintForm.pas' {frmEmpDocPrint},
  EmpDocumentForm in '..\Source\Common\EmployeeManagerForms\EmpDocumentForm.pas' {frmEmpDocument},
  EmpEstimateForm in '..\Source\Common\EmployeeManagerForms\EmpEstimateForm.pas' {frmEmpEstimate},
  EmpForSelectForm in '..\Source\Common\EmployeeManagerForms\EmpForSelectForm.pas' {frmEmpForSelect},
  EmpHistoryForm in '..\Source\Common\EmployeeManagerForms\EmpHistoryForm.pas' {frmEmpHistory},
  EmpInfoDataModule in '..\Source\Common\EmployeeManagerForms\EmpInfoDataModule.pas' {EmpInfoDM: TDataModule},
  EmpInfoForm in '..\Source\Common\EmployeeManagerForms\EmpInfoForm.pas' {frmEmpInfo},
  EmployeeListForm in '..\Source\Common\EmployeeManagerForms\EmployeeListForm.pas' {frmEmployees},
  EmpMissionForm in '..\Source\Common\EmployeeManagerForms\EmpMissionForm.pas' {frmEmpMission},
  EmpRewardDisciplineForm in '..\Source\Common\EmployeeManagerForms\EmpRewardDisciplineForm.pas' {frmEmpRewardDiscipline},
  EmpWageStandardForm in '..\Source\Common\EmployeeManagerForms\EmpWageStandardForm.pas' {frmEmpWageStandard},
  LocationListForm in '..\Source\Common\EmployeeManagerForms\LocationListForm.pas' {frmLocationList},
  LocationTypeList in '..\Source\Common\EmployeeManagerForms\LocationTypeList.pas' {frmLocationTypeList},
  MissionManager in '..\Source\Common\EmployeeManagerForms\MissionManager.pas' {frmMissionManager},
  NationListForm in '..\Source\Common\EmployeeManagerForms\NationListForm.pas' {frmNationList},
  OrganizationListForm in '..\Source\Common\EmployeeManagerForms\OrganizationListForm.pas' {frmOrganizationList},
  RaceListForm in '..\Source\Common\EmployeeManagerForms\RaceListForm.pas' {frmRaceList},
  RelationshipForm in '..\Source\Common\EmployeeManagerForms\RelationshipForm.pas' {frmRelationship},
  ReligionListForm in '..\Source\Common\EmployeeManagerForms\ReligionListForm.pas' {frmReligionList},
  ReportTemplateListForm in '..\Source\Common\EmployeeManagerForms\ReportTemplateListForm.pas' {frmReportTemplateList},
  WorkHistoryForm in '..\Source\Common\EmployeeManagerForms\WorkHistoryForm.pas' {frmWorkHistory},
  EstimateItemForm in '..\Source\Common\EstimateManagerForms\EstimateItemForm.pas' {frmEstimateItem},
  EstimateManagerForm in '..\Source\Common\EstimateManagerForms\EstimateManagerForm.pas' {frmEstimateManager},
  EstimateStageDetail in '..\Source\Common\EstimateManagerForms\EstimateStageDetail.pas' {frmEstimageStageDetail},
  EstimateStageSummary in '..\Source\Common\EstimateManagerForms\EstimateStageSummary.pas' {frmEstimateStageSummary},
  EstimateSysLevelForm in '..\Source\Common\EstimateManagerForms\EstimateSysLevelForm.pas' {frmEstimateSysLevel},
  DeptListForm in '..\Source\Common\OrganizationManagerForms\DeptListForm.pas' {frmDeptList},
  DeptTypeForm in '..\Source\Common\OrganizationManagerForms\DeptTypeForm.pas' {frmDeptType},
  OrganizationMapForm in '..\Source\Common\OrganizationManagerForms\OrganizationMapForm.pas' {frmOrganizationMap},
  PositionListForm in '..\Source\Common\OrganizationManagerForms\PositionListForm.pas' {frmPositionList},
  TitleListForm in '..\Source\Common\OrganizationManagerForms\TitleListForm.pas' {frmTitleList},
  WorkTypeForm in '..\Source\Common\OrganizationManagerForms\WorkTypeForm.pas' {frmWorkType},
  CandidatorCheckForm in '..\Source\Common\RecruitmentManagerForms\CandidatorCheckForm.pas' {frmCandidatorCheck},
  CandidatorForm in '..\Source\Common\RecruitmentManagerForms\CandidatorForm.pas' {frmCandidator},
  CreateCandidatorList in '..\Source\Common\RecruitmentManagerForms\CreateCandidatorList.pas' {frmCreateCandidatorList},
  InterviewForm in '..\Source\Common\RecruitmentManagerForms\InterviewForm.pas' {frmInterview},
  ProbationForm in '..\Source\Common\RecruitmentManagerForms\ProbationForm.pas' {frmProbation},
  RecruitmentManagerForm in '..\Source\Common\RecruitmentManagerForms\RecruitmentManagerForm.pas' {frmRecruitmentManager},
  RecruitmentPlanForm in '..\Source\Common\RecruitmentManagerForms\RecruitmentPlanForm.pas' {frmRecruitmentPlan},
  RecruitmentSourceForm in '..\Source\Common\RecruitmentManagerForms\RecruitmentSourceForm.pas' {frmRecruitmentSource},
  RecruitmentTestForm in '..\Source\Common\RecruitmentManagerForms\RecruitmentTestForm.pas' {frmRecruitmentTest},
  StudentSelectForm in '..\Source\Common\TrainingManagerForms\StudentSelectForm.pas' {frmStudentSelect},
  TrainingDeploymentForm in '..\Source\Common\TrainingManagerForms\TrainingDeploymentForm.pas' {frmTrainingDeployment},
  TrainingForm in '..\Source\Common\TrainingManagerForms\TrainingForm.pas' {frmTrainingForm},
  TrainingManagerForm in '..\Source\Common\TrainingManagerForms\TrainingManagerForm.pas' {frmTrainingManager},
  TrainingPlanForm in '..\Source\Common\TrainingManagerForms\TrainingPlanForm.pas' {frmTrainingPlan},
  TrainingSourceForm in '..\Source\Common\TrainingManagerForms\TrainingSourceForm.pas' {frmTrainingSource},
  TrainingSupplyForm in '..\Source\Common\TrainingManagerForms\TrainingSupplyForm.pas' {frmTrainingSupply},
  TrainingTypeForm in '..\Source\Common\TrainingManagerForms\TrainingTypeForm.pas' {frmTrainingType},
  GenerateVacationForm in '..\Source\Common\Vacation Manager\GenerateVacationForm.pas' {frmGenerateVacation},
  DefineWageMethodForm in '..\Source\Common\WageManagerForms\DefineWageMethodForm.pas' {frmDefineWageMethod},
  EmpWageStructureForm in '..\Source\Common\WageManagerForms\EmpWageStructureForm.pas' {frmEmpWageStructure},
  SSP_Math in '..\Source\Common\WageManagerForms\SSP_Math.pas',
  TaxForm in '..\Source\Common\WageManagerForms\TaxForm.pas' {frmTax},
  WageBookForm in '..\Source\Common\WageManagerForms\WageBookForm.pas' {frmWageBook},
  WageConstantForm in '..\Source\Common\WageManagerForms\WageConstantForm.pas' {frmWageConstantData},
  WageDataGenerateForm in '..\Source\Common\WageManagerForms\WageDataGenerateForm.pas' {frmWageDataGenerate},
  WageDataModule in '..\Source\Common\WageManagerForms\WageDataModule.pas' {WageDM: TDataModule},
  WageDiaryForm in '..\Source\Common\WageManagerForms\WageDiaryForm.pas' {frmWageDiary},
  WageElementForm in '..\Source\Common\WageManagerForms\WageElementForm.pas' {frmWageElement},
  WageElementTypeForm in '..\Source\Common\WageManagerForms\WageElementTypeForm.pas' {frmWageElementType},
  WageManagerForm in '..\Source\Common\WageManagerForms\WageManagerForm.pas' {frmWageManager},
  WageMethodAssignForm in '..\Source\Common\WageManagerForms\WageMethodAssignForm.pas' {frmWageMethodAssign},
  WageMethodAssignManagementForm in '..\Source\Common\WageManagerForms\WageMethodAssignManagementForm.pas' {frmWageMethodAssignManager},
  WageMethodForm in '..\Source\Common\WageManagerForms\WageMethodForm.pas' {frmWageMethod},
  WageParamForm in '..\Source\Common\WageManagerForms\WageParamForm.pas' {frmWageParamData},
  WagePlanForm in '..\Source\Common\WageManagerForms\WagePlanForm.pas' {frmWagePlan},
  WageStandardForm in '..\Source\Common\WageManagerForms\WageStandardForm.pas' {frmWageStandard},
  WageStructureForm in '..\Source\Common\WageManagerForms\WageStructureForm.pas' {frmWageStructure},
  CalendarForm in '..\Source\Common\WorkingTimeManagerForms\CalendarForm.pas' {frmCalendar},
  GenerateWorkDateTimeForm in '..\Source\Common\WorkingTimeManagerForms\GenerateWorkDateTimeForm.pas' {frmGenerateWorkDateTime},
  HolidayRegisterForm in '..\Source\Common\WorkingTimeManagerForms\HolidayRegisterForm.pas' {frmHolidayRegister},
  InitHolidayOptionForm in '..\Source\Common\WorkingTimeManagerForms\InitHolidayOptionForm.pas' {frmInitHolidayOption},
  InitHolidayTemplateForm in '..\Source\Common\WorkingTimeManagerForms\InitHolidayTemplateForm.pas' {frmInitHolidayTemplate},
  InitHolidayTimeTemplateForm in '..\Source\Common\WorkingTimeManagerForms\InitHolidayTimeTemplateForm.pas' {frmInitHolidayTimeTemplate},
  ToolForWorkDayForm in '..\Source\Common\WorkingTimeManagerForms\ToolForWorkDayForm.pas' {frmToolForWorkDay},
  ToolForWorkTotalForm in '..\Source\Common\WorkingTimeManagerForms\ToolForWorkTotalForm.pas' {frmToolForWorkTotal},
  WarningWorkTimeForm in '..\Source\Common\WorkingTimeManagerForms\WarningWorkTimeForm.pas' {frmWarningWorkTime},
  WorkDateTimeTypeForm in '..\Source\Common\WorkingTimeManagerForms\WorkDateTimeTypeForm.pas' {frmWorkDateHourType},
  WorkTimeCheckForm in '..\Source\Common\WorkingTimeManagerForms\WorkTimeCheckForm.pas' {frmWorkTimeCheck},
  WorkTimeDataModule in '..\Source\Common\WorkingTimeManagerForms\WorkTimeDataModule.pas' {WorkTimeDM: TDataModule},
  MaychamcongForm in '..\Source\Common\WorkingTimeManagerForms\Maychamcong\MaychamcongForm.pas' {frmMaychamcong},
  WorkTimeMachineManagerForm in '..\Source\Common\WorkingTimeManagerForms\WorkTimeMachineManagerForm.pas' {frmWorkTimeMachineManager},
  WorkTimeManagerForm in '..\Source\Common\WorkingTimeManagerForms\WorkTimeManagerForm.pas' {frmWorkTimeManager},
  LuongDacthu in '..\Source\HRM20\Luong\LuongDacthu.pas',
  MainUnit in '..\Source\HRM20\MainForms\MainUnit.pas' {frmMain},
  HamsoDacthu in '..\Source\HRM20\Thuvien\HamsoDacthu.pas',
  TrainingResultForm in '..\Source\Common\TrainingManagerForms\TrainingResultForm.pas' {frmTrainingResult},
  PopupMainForm in '..\Source\Common\FrameworkForms\MainForms\PopupMainForm.pas' {frmPopupMain},
  DateTimeFrame in '..\Source\Common\FrameworkForms\ToolForms\DateTimeFrame.pas' {frameDateTime: TFrame},
  WageProgressForm in '..\Source\Common\WageManagerForms\WageProgressForm.pas' {frmWageProgress},
  WageThread in '..\Source\Common\WageManagerForms\WageThread.pas',
  WorkTimeMachineForm in '..\Source\Common\WorkingTimeManagerForms\WorkTimeMachineForm.pas' {frmWorkTimeMachine},
  Maychamcong_CauhinhForm in '..\Source\Common\WorkingTimeManagerForms\Maychamcong\Maychamcong_CauhinhForm.pas' {frmMaychamcong_Cauhinh},
  FeatureListForm in '..\Source\Common\FrameworkForms\ToolForms\FeatureListForm.pas' {frmFeatureList},
  AuthorityConfigForm in '..\Source\Common\FrameworkForms\ToolForms\AuthorityConfigForm.pas' {frmAuthorityConfig},
  ChgNumToStr in '..\Source\Common\FrameworkForms\SSPLibrary\ChgNumToStr.pas',
  LogConfigForm in '..\Source\Common\FrameworkForms\LogData\LogConfigForm.pas' {frmLogConfig},
  LogDataForm in '..\Source\Common\FrameworkForms\ToolForms\LogDataForm.pas' {frmLogData},
  SSP_Compiler in '..\Source\Common\FrameworkForms\SSPLibrary\SSP_Compiler.pas',
  SendMailFrame in '..\Source\Common\FrameworkForms\ToolForms\SendMailFrame.pas' {frameSendMail: TFrame},
  ChucvuDoanForm in '..\Source\Common\EmployeeManagerForms\ChucvuDoanForm.pas' {frmChucvuDoan},
  AcademicListForm in '..\Source\Common\EmployeeManagerForms\AcademicListForm.pas' {frmAcademicList},
  ChucvuCDoanForm in '..\Source\Common\EmployeeManagerForms\ChucvuCDoanForm.pas' {frmChucvuCDoan},
  ChucvuDangForm in '..\Source\Common\EmployeeManagerForms\ChucvuDangForm.pas' {frmChucvuDang},
  RealtimeBackupForm in '..\Source\Common\FrameworkForms\ToolForms\RealtimeBackupForm.pas' {frmRealTimeBackup},
  MarrialStatusListForm in '..\Source\Common\EmployeeManagerForms\MarrialStatusListForm.pas' {frmMarrialStatus},
  TieuchuanPhepForm in '..\Source\Common\Vacation Manager\TieuchuanPhepForm.pas' {frmTieuchuanPhep},
  TheodoiPhepForm in '..\Source\Common\Vacation Manager\TheodoiPhepForm.pas' {frmTheodoiPhep},
  CapnhatPhepForm in '..\Source\Common\Vacation Manager\CapnhatPhepForm.pas' {frmCapnhatPhep},
  PhatsinhTieuchuanPhepForm in '..\Source\Common\Vacation Manager\PhatsinhTieuchuanPhepForm.pas' {frmPhatsinhTieuchuanPhep},
  DangkyPhepForm in '..\Source\Common\Vacation Manager\DangkyPhepForm.pas' {frmDangkyPhep},
  AlertConfigForm in '..\Source\Common\FrameworkForms\UserAlert\AlertConfigForm.pas' {frmAlertConfig},
  AlertBoardForm in '..\Source\Common\FrameworkForms\UserAlert\AlertBoardForm.pas' {frmAlertBoard},
  EstimateGroupForm in '..\Source\Common\EstimateManagerForms\EstimateGroupForm.pas' {frmEstimateGroup},
  TrainingConfigForm in '..\Source\Common\TrainingManagerForms\TrainingConfigForm.pas' {frmTrainingConfig},
  TrainingContentForm in '..\Source\Common\TrainingManagerForms\TrainingContentForm.pas' {frmTrainingContent},
  RecruitmentConfigForm in '..\Source\Common\RecruitmentManagerForms\RecruitmentConfigForm.pas' {frmRecruitmentConfig},
  SSP_Excel_Form in '..\Source\Common\FrameworkForms\ToolForms\SSP_Excel_Form.pas' {frmSSP_Excel},
  SSP_Excel_InsertPageForm in '..\Source\Common\FrameworkForms\ToolForms\SSP_Excel_InsertPageForm.pas' {frmSSP_Excel_InsertPage},
  SSP_Excel_Library in '..\Source\Common\FrameworkForms\ToolForms\SSP_Excel_Library.pas',
  SSP_Excel_Coder_Form in '..\Source\Common\FrameworkForms\ToolForms\SSP_Excel_Coder_Form.pas' {frmSSPExcelCoder},
  WorkTimeProcessForm in '..\Source\Common\WorkingTimeManagerForms\WorkTimeProcessForm.pas' {frmWorkTimeProcess},
  OffWorkReasonForm in '..\Source\Common\DecisionManagerForms\OffWorkReasonForm.pas' {frmOffWorkReason},
  WorkShiftListForm in '..\Source\Common\WorkingTimeManagerForms\WorkShiftListForm.pas' {frmWorkShiftList},
  WorkShiftRegForm in '..\Source\Common\WorkingTimeManagerForms\WorkShiftRegForm.pas' {frmWorkShiftReg},
  LoaiCongcu_Form in '..\Source\Common\InstrumentManager\LoaiCongcu_Form.pas' {frmCongcu_Loai},
  DanhmucCongcu_Form in '..\Source\Common\InstrumentManager\DanhmucCongcu_Form.pas' {frmCongcuDanhmuc},
  TrangthaiCongcu in '..\Source\Common\InstrumentManager\TrangthaiCongcu.pas' {frmCongcuTrangthai},
  CapphatCongcu_Form in '..\Source\Common\InstrumentManager\CapphatCongcu_Form.pas' {frmCongcuCapphat},
  ToolForWorkTimeForm in '..\Source\Common\WorkingTimeManagerForms\ToolForWorkTimeForm.pas' {frmToolForWorkTime},
  WorkingConfigForm in '..\Source\Common\WorkingTimeManagerForms\WorkingConfigForm.pas' {frmWorkingConfig},
  EmpListForm in '..\Source\Common\EmployeeManagerForms\EmpListForm.pas' {frmEmpList},
  EmpMoreInputForm in '..\Source\Common\EmployeeManagerForms\EmpMoreInputForm.pas' {frmEmpMoreInput},
  EmpListInputForm in '..\Source\Common\EmployeeManagerForms\EmpListInputForm.pas' {frmEmpListInput},
  SimpleSecurityLibrary in '..\Source\Common\FrameworkForms\SSPLibrary\SimpleSecurityLibrary.pas',
  CheckPackageForm in '..\Source\Common\FrameworkForms\SystemForms\CheckPackageForm.pas' {frmCheckPackage},
  ImportDataForm in '..\Source\Common\FrameworkForms\ToolForms\ImportDataForm.pas' {frmImportTool},
  EditImportRule in '..\Source\Common\FrameworkForms\ToolForms\EditImportRule.pas' {frmEditImportRule},
  UnicodeConvert in '..\Source\Common\FrameworkForms\SSPLibrary\UnicodeConvert.pas',
  TrainingCourseForm in '..\Source\Common\TrainingManagerForms\TrainingCourseForm.pas' {frmTrainingCourse},
  TrainingRegulationForm in '..\Source\Common\TrainingManagerForms\TrainingRegulationForm.pas' {frmTrainingRegulation},
  EmpPositionWizardForm in '..\Source\Common\DecisionManagerForms\EmpPositionWizardForm.pas' {frmEmpPositionWizard},
  DeleteLogDataForm in '..\Source\Common\FrameworkForms\ToolForms\DeleteLogDataForm.pas' {frmDeleteLogData},
  SkillListForm in '..\Source\Common\EmployeeManagerForms\SkillListForm.pas' {frmSkill},
  LanguageListForm in '..\Source\Common\EmployeeManagerForms\LanguageListForm.pas' {frmLanguage},
  TrainingAlertForm in '..\Source\Common\TrainingManagerForms\TrainingAlertForm.pas' {frmTrainingAlert},
  ContractGenerateForm in '..\Source\Common\ContractManagerForms\ContractGenerateForm.pas' {frmContractGenerate},
  ReviewTrainingPlanForm in '..\Source\Common\TrainingManagerForms\ReviewTrainingPlanForm.pas' {frmReviewTrainingPlan},
  TrainingBudgetForm in '..\Source\Common\TrainingManagerForms\TrainingBudgetForm.pas' {frmTrainingBudget},
  BuildScaleMatrixForm in '..\Source\Common\WageManagerForms\BuildScaleMatrixForm.pas' {frmBuildScaleMatrix},
  TrainingReportForm in '..\Source\Common\TrainingManagerForms\TrainingReportForm.pas' {frmTrainingReport},
  MenuListForm in '..\Source\Common\FrameworkForms\ListManagerForms\MenuListForm.pas' {frmMenuItem},
  DefineWageMatrixForm in '..\Source\Common\WageManagerForms\DefineWageMatrixForm.pas' {frmDefineWageMatrix},
  TrainingNewRegulationForm in '..\Source\Common\TrainingManagerForms\TrainingNewRegulationForm.pas' {frmTrainingNewReg},
  PhepNhapNhanhForm in '..\Source\Common\Vacation Manager\PhepNhapNhanhForm.pas' {frmPhepNhapNhanh},
  RewardManagementForm in '..\Source\Common\WageManagerForms\RewardManagementForm.pas' {frmRewardManagement},
  DocTuCCGioForm in '..\Source\Common\WorkingTimeManagerForms\DocTuCCGioForm.pas' {frmDocTuCCGio},
  RequestOutForm in '..\Source\Common\FrameworkForms\SystemForms\RequestOutForm.pas' {frmRequestOut},
  SSP_VersionInfo in '..\Source\Common\FrameworkForms\MainForms\SSP_VersionInfo.pas',
  PassLockWageBookForm in '..\Source\Common\WageManagerForms\PassLockWageBookForm.pas' {frmPassLockWageBook},
  ChangePassSalaryForm in '..\Source\Common\WageManagerForms\ChangePassSalaryForm.pas' {frmChangePassSalary},
  KiemTraChamCongForm in '..\Source\Common\WorkingTimeManagerForms\KiemTraChamCongForm.pas' {frmKiemTraChamCong},
  NhapGioForm in '..\Source\Common\WorkingTimeManagerForms\NhapGioForm.pas' {frmNhapGio},
  NhapNhanhLuongCBNNForm in '..\Source\Common\DecisionManagerForms\NhapNhanhLuongCBNNForm.pas' {frmNhapNhanhLuongCBNN},
  DieuDongWizardForm in '..\Source\Common\DecisionManagerForms\DieuDongWizardForm.pas' {frmDieuDongWizard},
  XDTochucPhapLyForm in '..\Source\Common\FrameworkForms\SystemForms\XDTochucPhapLyForm.pas' {frmXDTochucPhapLy},
  KhauTruThueKhacForm in '..\Source\Common\WageManagerForms\KhauTruThueKhacForm.pas' {frmKhauTruThueKhac},
  ChonNV_PAForm in '..\Source\Common\QuanlyLuong\ChonNV_PAForm.pas',
  Luong_Bangluong in '..\Source\Common\QuanlyLuong\Luong_Bangluong.pas' {frmLuong_Bangluong},
  Luong_ChitietBangForm in '..\Source\Common\QuanlyLuong\Luong_ChitietBangForm.pas' {frmLuong_ChitietBang},
  Luong_ChucvuForm in '..\Source\Common\QuanlyLuong\Luong_ChucvuForm.pas' {frmLuong_Chucvu},
  Luong_DataForm in '..\Source\Common\QuanlyLuong\Luong_DataForm.pas' {frmLuong_Data},
  Luong_DinhnghiaForm in '..\Source\Common\QuanlyLuong\Luong_DinhnghiaForm.pas' {frmLuong_Dinhnghia},
  Luong_DonviForm in '..\Source\Common\QuanlyLuong\Luong_DonviForm.pas' {frmLuong_Donvi},
  Luong_HamsoForm in '..\Source\Common\QuanlyLuong\Luong_HamsoForm.pas' {frmLuong_Hamso},
  Luong_MauinForm in '..\Source\Common\QuanlyLuong\Luong_MauinForm.pas' {frmLuong_Mauin},
  Luong_QuanlyForm in '..\Source\Common\QuanlyLuong\Luong_QuanlyForm.pas' {frmLuong_Quanly},
  Luong_SapchepForm in '..\Source\Common\QuanlyLuong\Luong_SapchepForm.pas' {frmLuong_Saochep},
  Luong_SapchepPAForm in '..\Source\Common\QuanlyLuong\Luong_SapchepPAForm.pas' {frmLuong_SaochepPA},
  Luong_SessionForm in '..\Source\Common\QuanlyLuong\Luong_SessionForm.pas' {frmLuongSession},
  Luong_TaoPAForm in '..\Source\Common\QuanlyLuong\Luong_TaoPAForm.pas' {frmLuong_TaoPA},
  Luong_Themnhanvien in '..\Source\Common\QuanlyLuong\Luong_Themnhanvien.pas',
  Luong_ThietkePAForm in '..\Source\Common\QuanlyLuong\Luong_ThietkePAForm.pas' {frmLuong_ThietkePA},
  Luong_Thread in '..\Source\Common\QuanlyLuong\Luong_Thread.pas',
  Luong_TienichNhaplieuForm in '..\Source\Common\QuanlyLuong\Luong_TienichNhaplieuForm.pas' {frmLuong_TienichNhaplieu},
  Luong_TinhluongForm in '..\Source\Common\QuanlyLuong\Luong_TinhluongForm.pas' {frmLuong_Tinhluong},
  Luong_ToolForm in '..\Source\Common\QuanlyLuong\Luong_ToolForm.pas' {frmLuong_Tuychon},
  Luong_VitriForm in '..\Source\Common\QuanlyLuong\Luong_VitriForm.pas' {frmLuong_Vitri},
  LuongDataModule in '..\Source\Common\QuanlyLuong\LuongDataModule.pas' {dmLuong: TDataModule},
  SSP_Luong in '..\Source\Common\QuanlyLuong\SSP_Luong.pas',
  SelectEmployeeBaseForm in '..\Source\Common\EmployeeManagerForms\SelectEmployeeBaseForm.pas' {frmSelectEmployee},
  Luong_KhoaLuongForm in '..\Source\Common\QuanlyLuong\Luong_KhoaLuongForm.pas' {frmLuong_KhoaLuong},
  EmpCalendarWizardForm in '..\Source\Common\WorkingTimeManagerForms\EmpCalendarWizardForm.pas' {frmEmpCalendarWizard},
  DieuDongToolForm in '..\Source\HRM30\QLViTriCongTac\DieuDongToolForm.pas' {frmDieuDongTool},
  FastOM_ToolForm in '..\Source\HRM30\QLViTriCongTac\FastOM_ToolForm.pas' {frmFastOM_Tool},
  NghiViecToolForm in '..\Source\HRM30\QLViTriCongTac\NghiViecToolForm.pas' {frmNghiViecTool},
  DMTinTucForm in '..\Source\HRM30\WEB\DMTinTucForm.pas' {frmDMTinTuc},
  CauHinhSuaThongTinNhanVienForm in '..\Source\HRM30\WEB\CauHinhSuaThongTinNhanVienForm.pas' {frmCauHinhSuaThongTinNhanVien},
  CapNhatThongTinNVForm in '..\Source\HRM30\WEB\CapNhatThongTinNVForm.pas' {frmCapNhatThongTinNV},
  DanhSachQDAoForm in '..\Source\Common\DecisionManagerForms\DanhSachQDAoForm.pas' {frmDanhSachQDAo},
  GioiThieuForm in '..\Source\Common\FrameworkForms\LicenseForms\GioiThieuForm.pas' {frmGioiThieu},
  CauHinh_DangKy_PhepForm in '..\Source\Common\Vacation Manager\CauHinh_DangKy_PhepForm.pas' {frmCauHinh_DangKy_Phep},
  PopupBaoHiemForm in '..\Source\Common\BaoHiemForms\PopupBaoHiemForm.pas' {frmPopupBaoHiem},
  BAOHIEM_BangDuLieuForm in '..\Source\Common\BaoHiemForms\BAOHIEM_BangDuLieuForm.pas' {frmBAOHIEM_BangDuLieu},
  BAOHIEM_BenhVienForm in '..\Source\Common\BaoHiemForms\BAOHIEM_BenhVienForm.pas' {frmBAOHIEM_BenhVien},
  BAOHIEM_CauHinhDuLieuForm in '..\Source\Common\BaoHiemForms\BAOHIEM_CauHinhDuLieuForm.pas' {frmBAOHIEM_CauHinhDuLieu},
  BAOHIEM_CauHinhForm in '..\Source\Common\BaoHiemForms\BAOHIEM_CauHinhForm.pas' {frmBAOHIEM_CauHinh},
  BAOHIEM_ChinhSachForm in '..\Source\Common\BaoHiemForms\BAOHIEM_ChinhSachForm.pas' {frmBAOHIEM_ChinhSach},
  BAOHIEM_DataModule in '..\Source\Common\BaoHiemForms\BAOHIEM_DataModule.pas' {dmBAOHIEM: TDataModule},
  BAOHIEM_DinhNghiaForm in '..\Source\Common\BaoHiemForms\BAOHIEM_DinhNghiaForm.pas' {frmBAOHIEM_DinhNghia},
  BAOHIEM_DSPHSK_SauOmForm in '..\Source\Common\BaoHiemForms\BAOHIEM_DSPHSK_SauOmForm.pas' {frmBAOHIEM_DSPHSK_SauOm},
  BAOHIEM_DSPHSK_SauTNLDForm in '..\Source\Common\BaoHiemForms\BAOHIEM_DSPHSK_SauTNLDForm.pas' {frmBAOHIEM_DSPHSK_SauTNLD},
  BAOHIEM_DSPHSK_SauTSForm in '..\Source\Common\BaoHiemForms\BAOHIEM_DSPHSK_SauTSForm.pas' {frmBAOHIEM_DSPHSK_SauTS},
  BAOHIEM_GetDataForm in '..\Source\Common\BaoHiemForms\BAOHIEM_GetDataForm.pas' {frmBAOHIEM_GetData},
  BAOHIEM_HamSoForm in '..\Source\Common\BaoHiemForms\BAOHIEM_HamSoForm.pas' {frmBAOHIEM_HamSo},
  BAOHIEM_MauInForm in '..\Source\Common\BaoHiemForms\BAOHIEM_MauInForm.pas' {frmBAOHIEM_MauIn},
  BAOHIEM_MucDoSuyGiamForm in '..\Source\Common\BaoHiemForms\BAOHIEM_MucDoSuyGiamForm.pas' {frmBAOHIEM_MucDoSuyGiam},
  BAOHIEM_MucDoThuongTatForm in '..\Source\Common\BaoHiemForms\BAOHIEM_MucDoThuongTatForm.pas' {frmBAOHIEM_MucDoThuongTat},
  BAOHIEM_NghiKhongLuongForm in '..\Source\Common\BaoHiemForms\BAOHIEM_NghiKhongLuongForm.pas' {frmBAOHIEM_NghiKhongLuong},
  BAOHIEM_NghiOmForm in '..\Source\Common\BaoHiemForms\BAOHIEM_NghiOmForm.pas' {frmBAOHIEM_NghiOm},
  BAOHIEM_NhapPhieu_KCBForm in '..\Source\Common\BaoHiemForms\BAOHIEM_NhapPhieu_KCBForm.pas' {frmBAOHIEM_NhapPhieu_KCB},
  BAOHIEM_PhanNhomForm in '..\Source\Common\BaoHiemForms\BAOHIEM_PhanNhomForm.pas' {frmBAOHIEM_PhanNhom},
  BAOHIEM_SessionForm in '..\Source\Common\BaoHiemForms\BAOHIEM_SessionForm.pas' {frmBAOHIEM_Session},
  BAOHIEM_SoDangKyForm in '..\Source\Common\BaoHiemForms\BAOHIEM_SoDangKyForm.pas' {frmBAOHIEM_SoDangKy},
  BAOHIEM_TaiNanLaoDongForm in '..\Source\Common\BaoHiemForms\BAOHIEM_TaiNanLaoDongForm.pas' {frmBAOHIEM_TaiNanLaoDong},
  BAOHIEM_TaoBangDuLieuForm in '..\Source\Common\BaoHiemForms\BAOHIEM_TaoBangDuLieuForm.pas' {frmBAOHIEM_TaoBangDuLieu},
  BAOHIEM_TaoMauForm in '..\Source\Common\BaoHiemForms\BAOHIEM_TaoMauForm.pas' {frmBAOHIEM_TaoMau},
  BAOHIEM_ThaiSan_KHHForm in '..\Source\Common\BaoHiemForms\BAOHIEM_ThaiSan_KHHForm.pas' {frmBAOHIEM_ThaiSan_KHH},
  BAOHIEM_ThietKeMauForm in '..\Source\Common\BaoHiemForms\BAOHIEM_ThietKeMauForm.pas' {frmBAOHIEM_ThietKeMau},
  BAOHIEM_TienIchNhapLieuForm in '..\Source\Common\BaoHiemForms\BAOHIEM_TienIchNhapLieuForm.pas' {frmBAOHIEM_TienIchNhapLieu},
  BAOHIEM_TinhThanhPhoForm in '..\Source\Common\BaoHiemForms\BAOHIEM_TinhThanhPhoForm.pas' {frmBAOHIEM_TinhThanhPho},
  BAOHIEM_TNLD_NguyenNhanForm in '..\Source\Common\BaoHiemForms\BAOHIEM_TNLD_NguyenNhanForm.pas' {frmBAOHIEM_TNLD_NguyenNhan},
  BAOHIEM_YeuToChanThuongForm in '..\Source\Common\BaoHiemForms\BAOHIEM_YeuToChanThuongForm.pas' {frmBAOHIEM_YeuToChanThuong},
  BHXH_TTSuckhoeForm in '..\Source\Common\BaoHiemForms\BHXH_TTSuckhoeForm.pas' {frmBHXH_TTSuckhoe},
  NhapSoSoLDForm in '..\Source\Common\BaoHiemForms\NhapSoSoLDForm.pas' {frmNhapSoSoLD},
  BAOHIEM_ChonNVForm in '..\Source\Common\BaoHiemForms\BAOHIEM_ChonNVForm.pas' {frmBAOHIEM_ChonNV},
  UserWebForm in '..\Source\HRM30\WEB\UserWebForm.pas' {frmUserWeb},
  BAOHIEM_TienIchNhapSoForm in '..\Source\Common\BaoHiemForms\BAOHIEM_TienIchNhapSoForm.pas' {frmBAOHIEM_TienIchNhapSo},
  LaborLicenseForm in '..\Source\Common\EmployeeManagerForms\LaborLicenseForm.pas' {frmLaborlicense},
  Luong_NhanVienForm in '..\Source\Common\QuanlyLuong\Luong_NhanVienForm.pas' {frmLuong_NhanVien},
  Luong_NhanVienToolForm in '..\Source\Common\QuanlyLuong\Luong_NhanVienToolForm.pas' {frmLuong_NhanVienTool},
  Luong_SaoChepToolForm in '..\Source\Common\QuanlyLuong\Luong_SaoChepToolForm.pas' {frmLuong_SaoChepTool},
  BangTheoDoiCongTacForm in '..\Source\Common\EmployeeManagerForms\BangTheoDoiCongTacForm.pas' {frmBangTheoDoiCongTac},
  WageCompanyForm in '..\Source\Common\QuanlyLuong\WageCompanyForm.pas' {frmWageCompany},
  NhapNhanhLuongCongTyForm in '..\Source\Common\DecisionManagerForms\NhapNhanhLuongCongTyForm.pas' {frmNhapNhanhLuongCongTy},
  BoiHoanDaoTaoForm in '..\Source\Common\TrainingManagerForms\BoiHoanDaoTaoForm.pas' {frmBoiHoanDaoTao},
  TrainingPhanLoaiForm in '..\Source\Common\TrainingManagerForms\TrainingPhanLoaiForm.pas' {frmTrainingPhanLoai},
  Theodoinangluongfrm in '..\Source\Common\EmployeeManagerForms\OSC\Theodoinangluongfrm.pas' {frmTheodoinangluong};

{$R *.res}
begin
  Application.Initialize;
  HRSplash_Form := THRSplash_Form.Create(Application);
  HRSplash_Form.Show;
  HRSplash_Form.Update;
  Application.Title := 'HRM 3.0';
  Application.HelpFile := 'HDSD-HRM';
  Application.CreateForm(TdmMain, dmMain);
  frmLogin:=TfrmLogin.Create(Application);
  with frmLogin do
  try
    if ShowModal = mrOK then
    begin
      Screen.Cursor := crSQLWait;
      Free;
      HRSplash_Form.Update;
      dmMain.InitData;
      Application.CreateForm(TfrmMain, frmMain);
      Application.CreateForm(TfrmPopupMain, frmPopupMain);
      Application.CreateForm(TEmpInfoDM, EmpInfoDM);
      Application.CreateForm(TDecisionDM, DecisionDM);
      Application.CreateForm(TContractDM, ContractDM);
      Application.CreateForm(TWorkTimeDM, WorkTimeDM);
      Application.CreateForm(TWageDM, WageDM);
      Application.CreateForm(TdmLuong, dmLuong);
      Application.CreateForm(TdmBAOHIEM, dmBAOHIEM);
      Application.CreateForm(TfrmPopupBaoHiem, frmPopupBaoHiem);      
      Screen.Cursor := crDefault;
    end
    else
    begin
      Free;
      Application.Terminate;
    end;
  finally

  end;
  HRSplash_Form.Hide;
  HRSplash_Form.Free;
  Application.Run;
end.

